import fs from 'fs/promises';
import path from 'path';
import yaml from 'js-yaml';
import { fileURLToPath } from 'url';
import { summarizeText } from '../services/llm.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * GET /api/workflows/:id/details
 * Get detailed workflow information with AI explanation
 */
export async function getWorkflowDetails(req, res) {
  try {
    const { id } = req.params;

    if (!id) {
      return res.status(400).json({
        success: false,
        error: 'Workflow ID is required'
      });
    }

    const workflowDir = path.join(__dirname, '../../workflows', id);
    const yamlPath = path.join(workflowDir, `${id}.yaml`);

    // Check if workflow exists
    try {
      await fs.access(yamlPath);
    } catch {
      return res.status(404).json({
        success: false,
        error: 'Workflow not found'
      });
    }

    // Read YAML file
    const yamlContent = await fs.readFile(yamlPath, 'utf-8');
    const workflowData = yaml.load(yamlContent);

    // Extract tasks information
    const tasks = (workflowData.tasks || []).map(task => ({
      id: task.id,
      name: task.id,
      description: `Executes: ${task.commands ? task.commands.join(', ') : 'No commands'}`
    }));

    // Generate AI explanation
    const explanationPrompt = `Explain this workflow in 2-3 sentences for a non-technical user:\n\nWorkflow: ${id}\nDescription: ${workflowData.description}\nTasks: ${tasks.length}`;
    
    let explanation = workflowData.description || 'Automated workflow generated by AI';
    try {
      // Try to get AI explanation, but don't fail if it doesn't work
      explanation = await summarizeText(explanationPrompt);
    } catch (error) {
      console.log('Using fallback explanation:', error.message);
    }

    res.json({
      success: true,
      details: {
        yaml: yamlContent,
        explanation: explanation,
        tasks: tasks
      }
    });

  } catch (error) {
    console.error('Error fetching workflow details:', error);
    res.status(500).json({
      success: false,
      error: error.message
    });
  }
}

export default getWorkflowDetails;
